Default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  host: localhost

development:
  <<: *default
  database: mdzz_development

test:
  <<: *default
  database: mdzz_test

production:
  <<: *default
  database: mdzz_development
  username: mdzz
  password: <%= ENV['MDZZ_DATABASE_PASSWORD'] %>
